PimaIndians<- read.csv("C://Documents and Settings/farzad/Desktop/New Folder/PimaIndians.csv")
plot(PimaIndians)
PI=data.frame(PimaIndians)
mm1=glm(Class~.,family=binomial,data=PI)
mm1
summary(mm1)
RPI=PI[,-4]
mm1=glm(Class~.,family=binomial,data=RPI)
mm1
summery(mm1)
summary(mm1)
RPI=RPI[,-7]
mm1=glm(Class~.,family=binomial,data=RPI)
mm1
summary(mm1)
RPI=RPI[,-4]
RPI[1:3,]
mm1=glm(Class~.,family=binomial,data=RPI)
mm1
summary(mm1)
set.seed(1)
n=length(PI$Class)
n
n1=floor(n*(0.5))
n1
n2=n-n1
n2
train=sample(1:n,n1)
PI1=data.frame(PI[train,])
PI2=data.frame(PI[-train,])
mm2=glm(Class~.,family=binomial,data=PI1)
mm2
summary(mm2)
gg=predict(mm2,newdata=PI2,type= "response")
gg
hist(gg)
plot(PI$Class[-train]~gg)
gg1=floor(gg+0.5)
ttt=table(PI$Class[-train],gg1)
ttt
error=(ttt[1,2]+ttt[2,1])/n2
error
mm2=glm(Class~NuPregnancy+Glucose+DiastolicBP+BodyMassIndex+DiabetesPedigree,family=binomial,data=PI1)
mm2
summary(mm2)
gg=predict(mm2,newdata=PI2,type= "response")
gg
hist(gg)
plot(PI$Class[-train]~gg)
gg1=floor(gg+0.5)
ttt=table(PI$Class[-train],gg1)
ttt
error=(ttt[1,2]+ttt[2,1])/n2
error